### PR TITLE
Implemented missing properties to Notification Model

### PR DESCRIPTION
**Pull request by hppycoder**
Found that the "category" and "decision_code" was missing from the Notification Model class.

### CODE REVIEW

**Comment by hppycoder** [comment]
Thanks for merging, would you be able to create a release and update Packagist?

**Comment by dormini** [comment]
just did, thanks for your help on this. 
packagist should update automatically in a short while.

**Comment by hppycoder** [comment]
Thanks, would you mind logging in and updating Packagist? We need to pull this in and keep testing the new feature.

**Comment by dormini** [comment]
wish i could, seems that @stephenjwinn has control over our listing at packagist. 
maybe he can help out here?

**Pull request merged**
